#!/bin/busybox sh
# vim: set ft=sh:

# Normally, ROOT_DIR is empty. For testing export and set it pointing to initramfs rootfs dir.
. $ROOT_DIR/etc/unlocker.conf

UNLOCKED=0

# at first, nothing seem to happen... until space, enter, "x" or "c" is pressed
plymouth watch-keystroke $'--keys="xXcC \n"' >/tmp/plykey || exit 1

# when it's "x", after the disk is unlocked we'll show some extra boot options
grep -qi 'x' /tmp/plykey && touch /tmp/do.advanced_selection
# when it's "c", show drop to console after disk is unlocked
grep -qi 'c' /tmp/plykey && touch /tmp/do.console_drop
rm -f /tmp/plykey

# ok, ask for password
for try in `seq 1 3`; do
	plymouth --ping || exit 1
	plymouth ask-for-password --prompt="Please enter unlock passphrase:" --dont-pause-progress \
		| sed-opal-unlocker decryptpasswd "$ROOT_DIR/$UC_DISK_ENCR_KEY_FILE" "/tmp/disk.pass"
	sed-opal-unlocker unlock,MBRunshadow "$UC_DISK_TO_UNLOCK" "/tmp/disk.pass"
	[ $? -eq 0 ] && UNLOCKED=1
	[ $UNLOCKED -eq 1 ] && break
done
[ "$UC_PASS_UNLOCK_CREDS" -eq "1" ] || shred -n 3 -z -u "/tmp/disk.pass"

# and finally...
if [ $UNLOCKED -eq 1 ]; then
	rm -f /tmp/wait.for.me
	exit 0
else
	plymouth pause-progress
	plymouth display-message --text="Access denied. Please power cycle to try again."
	exit 1
fi
